### ISSUE TITLE
SCAR-H is broken

### ISSUE THREAD

**Issue by Freezgam03** [civilgamers/SCP_Public_Development#82]
When you ADS it doesn't aim exactly where you're looking and when you shoot the bullets are very off center of the scope, this was supposed to be fixed in the lastest change log

**Comment by Freezgam03** [comment]
Fixed on US appearantly?

**Comment by Copeless** [comment]
Should be fixed on both live servers tomorrow, when confirmed please assign completed

**Comment by Freezgam03** [comment]
@Copeless Still not fixed on US, the scope is off-center

**Comment by Kw1ll** [comment]
Tested this 29/08/2022 3pm, still broken/slightly misaligned @Copeless (pl0x fix mwah)
